services:
  qdrant:
    image: qdrant/qdrant:latest
    container_name: qdrant_rag
    restart: unless-stopped
    ports:
      - "6333:6333" # REST API & Web Dashboard
      - "6334:6334" # gRPC API
    volumes:
      - qdrant_storage:/qdrant/storage
    environment:
      - QDRANT__SERVICE__ENABLE_STATIC_CONTENT=1

volumes:
  qdrant_storage:
    name: qdrant_rag_storage
